version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/node:20.0
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm ci --ignore-scripts
      - run:
          name: Run Tests
          command: |
            npm run test:cov
      - run:
          name: Deploy to HackerRank
          command: |
            # Configuramos git para el push
            git config --global user.email "jmanyoma@fgs.co"
            git config --global user.name "Edwin Manyoma"
            # HACKERRANK_REPO_URL debe estar en los Project Settings de CircleCI
            git remote add hackerrank $HACKERRANK_REPO_URL
            git push hackerrank HEAD:master --force

workflows:
  version: 2
  market_items_workflow:
    jobs:
      - build_and_test:
          filters:
            branches:
              only:
                - main
                - node-solution
