version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@4.0.0 #

jobs:
  build_and_test:
    docker:
      - image: cimg/node:20.0 #
    working_directory: ~/project.
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            # Entramos a la carpeta del proyecto si es necesario
            npm ci --ignore-scripts #
      - run:
          name: Run Tests and Coverage
          command: |
            npm run test:cov # Genera lcov.info para SonarCloud

      # Paso de escaneo de SonarCloud
      - sonarcloud/scan #

      - run:
          name: Deploy to Render
          command: |
            if [ -n "${RENDER_DEPLOY_HOOK}" ]; then
              echo "Triggering Render Deploy..."
              curl -X POST "${RENDER_DEPLOY_HOOK}"
            else
              echo "RENDER_DEPLOY_HOOK not set. Skipping auto-deployment."
            fi

workflows:
  version: 2
  market_items_workflow:
    jobs:
      - build_and_test:
          context: sonarcloud # Requerido para leer el SONAR_TOKEN
          filters:
            branches:
              only:
                - main
                - node-solution
