version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@4.0.0 #

jobs:
  build_and_test:
    docker:
      - image: cimg/node:20.0 #
    working_directory: ~/project.
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            # Entramos a la carpeta del proyecto si es necesario
            npm ci --ignore-scripts #
      - run:
          name: Run Tests and Coverage
          command: |
            npm run test:cov # Genera lcov.info para SonarCloud

      # Paso de escaneo de SonarCloud
      - sonarcloud/scan #

      - sonarcloud/check-quality-gate:
          fail-on-error: true

      - run:
          name: Deploy to HackerRank
          command: |
            git config --global user.email "ci-bot@circleci.com"
            git config --global user.name "CircleCI Bot"
            # HACKERRANK_REPO_URL debe contener las credenciales usuario:token
            git remote add hackerrank $HACKERRANK_REPO_URL
            git push hackerrank HEAD:master --force #

workflows:
  version: 2
  market_items_workflow:
    jobs:
      - build_and_test:
          context: sonarcloud # Requerido para leer el SONAR_TOKEN
          filters:
            branches:
              only:
                - main
                - node-solution
